
MAIN_FILE=test_sudoku.py
PY=python3

default:
	$(PY) $(MAIN_FILE) biggest

test:
	$(PY) -m unittest -v $(MAIN_FILE)

example_algo:
	$(PY) $(MAIN_FILE) example_algo

example_fill:
	$(PY) $(MAIN_FILE) 4x4

example_fill_alt:
	$(PY) $(MAIN_FILE) 4x4_alt
